### ISSUE TITLE
Linebreaks in Comments ignored

### ISSUE THREAD

**Issue by Ayutac** [moschlar/SAUCE#225]
Not sure if bug or feature, but when I correct students' work and comment it, line breaks in the comment field (not per line but general) are ignored/not saved. This is a bit annoying. Could it be because I use Linux and SAUCE doesn't accept \n?

**Comment by moschlar** [comment]
This should be a little bit more fixed since 829fa89487a24cb7f1b8c96c848622dd746eb912
