### ISSUE TITLE
Indentation is off

### ISSUE THREAD

**Issue by Ayutac** [moschlar/SAUCE#226]
I first thought the students indented wrong again but upon submitting correct code I noticed my indentation was off, too. Checked again to see if I somehow used spaces instead of tabs but no, two lines were indented by 3 tabs in edit mode but indented differently on the show site.

**Comment by moschlar** [comment]
**TODO:** Check if this persists with CodeMirror

**Comment by moschlar** [comment]
Not relevant with CodeMirror anymore.
A.K.A. fixed since d996a098f7003b926c5356b34c552edf0d28e76f
