### ISSUE TITLE
Der Name des Autors ist der Redaktion bekannt

### ISSUE THREAD

**Issue by gravitino** [moschlar/SAUCE#236]
// Es folgt eine Ode an SAUCE:
        /////////////////////////////////
        // Oh du System der Erleichterung,
        // du multilinguales Validierungsgenie,
        // du wunderbare Umsetzung.
        // Deine JQuery Templates überstrahlen,
        // deine Funktionalität,
        // und vorallem die Qualen,
        // die man erleidet,
        // man fast aus Wut dahinscheidet.
        //
        // Session timeouts setzt du durch,
        // als wäre zwischen deinen Zähnen ein Messer,
        // warum auch nicht?
        // Schreib ich alles nochmal,
        // denn doppelt hält besser.
        //
        // So nimm hin meinen Code,
        // den ich aus meinem Kopfe zog,
        // und führe ihn aus,
        // *TIMEOUT OCCURED!*
        // aus die Maus.
        // \0

        //in diesem Sinne: alle Abgaben sind ungetestet da SAUCE wiedermal den timeout Fehler hat (15.01., 00:34) ...

**Comment by moschlar** [comment]
Als Instanz-spezifische Frage ist das hier schlecht aufgehoben.
Aber es ist sicherlich ein Wink mit dem Zaunpfahl für #141 .
