### ISSUE TITLE
Line numbers and actual code lines are shifted

### ISSUE THREAD

**Issue by limbach** [moschlar/SAUCE#93]
I'm using Firefox 16.0.2 under Ubuntu 10.04 and the lining up of line numbers and code lines is inconsistent, as long as I use the default font-size. See, for example, https://sauce.zdv.uni-mainz.de/submissions/151/judge 

At the beginning of the code, the line numbers start below the second code line, at the end the line numbers are ending before the actual code lines come to an end. 

As soon as I increase or decrease the font size, the lining up changes and is correct for some size settings. The problem occurs in the Show, as well as in the Judge view.

Remark: Martin could not reproduce this issue using OpenSuse and the same browser version.

**Comment by moschlar** [comment]
This should be obsoleted with CodeMirror since d996a098f7003b926c5356b34c552edf0d28e76f
